# Generated by Django 4.0.1 on 2022-01-16 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('birth_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secretary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('reservation_schedule', models.CharField(max_length=255)),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.secretary')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_status', models.CharField(choices=[('C', 'COMPLETE'), ('R', 'REJECTED')], default='C', max_length=1)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='reservation.applicant')),
                ('lawyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.lawyer')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.secretary')),
            ],
        ),
    ]
