# Generated by Django 4.0.1 on 2022-01-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_applicant_visa_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicant',
            old_name='first_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='applicant',
            old_name='last_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='secretary',
            name='email',
        ),
    ]
