# Generated by Django 4.0.1 on 2022-01-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lawyer',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='secretary',
            old_name='first_name',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='secretary',
            old_name='last_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='lawyer',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='visa_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='reservation_schedule',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
