# Generated by Django 4.0.1 on 2022-01-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0005_rename_first_name_lawyer_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='password',
            field=models.CharField(default='adminadmin1', max_length=255),
        ),
    ]
